#!/bin/bash
if [ -n "$1" ]; then
    sed "s/replaceme/$1/g" /etc/bind/zones/.db.default > /etc/bind/zones/db."$1"carl-vanderwegen.sb.uclllabs.be
    #zonefile
    sed "s/replaceme/$1/g" /etc/bind/.addon_named.conf.local >> /etc/bind/named.conf.local
    #add record in base file
    echo "@     IN      NS      ns.$1.carl-vanderwegen.sb.uclllabs.be." >> /etc/bind/zones/db.carl-vanderwegen.sb.uclllabs.be 
else
    echo "enter something pls"
fi
