#!/bin/bash
if [ -n "$1" ]; then
    sed "s/replaceme/$1/g" /etc/bind/zones/.db.default > /etc/bind/zones/db."$1".carl-vanderwegen.sb.uclllabs.be
    #zonefile
    sed "s/replaceme/$1/g" /etc/bind/.addon_named.conf.local >> /etc/bind/named.conf.local
    #add record in base file
    printf "\n$1     IN      NS      ns.carl-vanderwegen.sb.uclllabs.be.\n" >> /etc/bind/zones/db.carl-vanderwegen.sb.uclllabs.be 

    SERIAL_NUM=$(grep -Po '\d+(?=\s+; Serial)' db.carl-vanderwegen.sb.uclllabs.be)
    SERIAL_LIN=$(grep -Po '\s+; Serial' db.carl-vanderwegen.sb.uclllabs.be)
    SERIAL_ALL=$(grep -Po '\d+\s+; Serial' db.carl-vanderwegen.sb.uclllabs.be)
    NEW_NUM=$(("$SERIAL_NUM" + 1))
    sed -i "s/$SERIAL_ALL/$NEW_NUM$SERIAL_LIN/g" db.carl-vanderwegen.sb.uclllabs.be
    service bind9 restart
else
    printf "enter something pls"
fi
