#!/bin/bash
if [ -n "$1" ]; then
    if [[ $1 = "-t" ]]; then
        case $2 in
            A )
                printf "\n$3  IN  A  $4"  >> /etc/bind/zones/db."$5"
                ZONEFILE="/etc/bind/zones/db.$5"
                ;;
            MX )
                printf "\n@    IN MX $3" >> /etc/bind/zones/db."$5"
                printf "\n$3   IN  A $4" >> /etc/bind/zones/db."$5"
                ZONEFILE="/etc/bind/zones/db.$5"
                ;;
            CNAME )
		ZONEF=$(cut -d. -f2- "$4")
                ZONEFILE="/etc/bind/zones/db.$ZONEF"
                printf "\n$3    IN    CNAME    $4\n">> "$ZONEFILE"
                ;;
        esac
    else
        printf "$1"  IN  A  "$2"  >> /etc/bind/zones/db."$3"
        ZONEFILE="/etc/bind/zones/db.$3"
    fi
    SERIAL_NUM=$(grep -Po '\d+(?=\s+; Serial)' "$ZONEFILE")
    SERIAL_LIN=$(grep -Po '\s+; Serial' "$ZONEFILE")
    SERIAL_ALL=$(grep -Po '\d+\s+; Serial' "$ZONEFILE")
    NEW_NUM=$(("$SERIAL_NUM" + 1))
    sed -i "s/$SERIAL_ALL/$NEW_NUM$SERIAL_LIN/g" "$ZONEFILE"
    service bind9 restart
else
    printf "angry typing"
fi