#!/bin/bash
if [[ $1 = "-t" ]]; then
    case $2 in
        A )
            echo "$3"  IN  A  "$4"  >> /etc/bind/zones/db."$5"
            ZONEFILE="/etc/bind/zones/db.$5"
            ;;
        MX )
            echo @    IN MX "$3" >> /etc/bind/zones/db."$5"
            echo "$3"   IN  A "$4" >> /etc/bind/zones/db."$5"
            ZONEFILE="/etc/bind/zones/db.$5"
            ;;
        CNAME )
            echo "$3"    IN    CNAME    "$4">> /etc/bind/zones/db.carl-vanderwegen.sb.uclllabs.be
            # moet dit ook voor andere zones?
            echo "$3"  IN  A  "$4"  >> /etc/bind/zones/db."$5"
            ZONEFILE="/etc/bind/zones/db.$5"
            ;;
    esac
else
    echo "$1"  IN  A  "$2"  >> /etc/bind/zones/db."$3"
    ZONEFILE="/etc/bind/zones/db.$3"
fi
SERIAL_NUM=$(grep -Po '\d+(?=\s+; Serial)' "$ZONEFILE")
SERIAL_LIN=$(grep -Po '\s+; Serial' "$ZONEFILE")
SERIAL_ALL=$(grep -Po '\d+\s+; Serial' "$ZONEFILE")
NEW_NUM=$(("$SERIAL_NUM" + 1))
sed -i "s/$SERIAL_ALL/$NEW_NUM$SERIAL_LIN/g" "$ZONEFILE"