#!/bin/bash
ZONE=$(grep -Po '.{1,}(?=.carl-vanderwegen.sb.uclllabs.be)' <<< "$1")
EXIST='grep -P '^"$ZONE"\s' /etc/bind/zones/db.carl-vanderwegen.sb.uclllabs.be | wc -l'

if [ "$EXIST" -gt 0 ]; then
    cp -r /var/www/html/.defaulthost /var/www/html/"ZONE"
    sed "s/replaceme/$ZONE/g" /etc/apache2/sites-available/.default_http.conf > /etc/apache2/sites-available/"$ZONE".conf
    sed -i '# --- END PVE ---/i \
    193.191.177.139 $1' /etc/hosts
    a2ensite "$ZONE".conf
    systemctl reload apache2

else
    echo "your zone doesn't exist"
fi
