#!/bin/bash
ZONE=$(grep -Po '.{1,}(?=.carl-vanderwegen.sb.uclllabs.be)' <<< "$1")
POL=$(cut -d'.' -f2 <<< "$1")
P1=$(cut -d'.' -f1 <<< "$1")
MINPOL=$(cut -d'.' -f2- <<< "$1")
EXIST=$(grep -P '^"$P1"\s' /etc/bind/zones/db."$MINPOL" | wc -l)

if [ "$EXIST" > 0 ]; then
    cp -r /var/www/html/.defaulthost /var/www/html/"$ZONE"
    sed "s/replaceme/$ZONE/g" /etc/apache2/sites-available/.default_http.conf > /etc/apache2/sites-available/000-"$ZONE".conf
    a2ensite 000-"$ZONE".conf
    systemctl reload apache2
else
    echo "your zone doesn't exist"
exit 1
fi