---
- hosts: apache
  become: sudo
  tasks:
    - name: install apache2
      apt: name=apache2
    - copy:
        src: /etc/ansible/apache_dirs/var.www/
        dest: /var/www/
    - copy:
        src: /etc/ansible/apache_dirs/etc.apache2/
        dest: /etc/apache2/
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted